language: python
python:
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install -r requirements_test.txt
before_script:
 - python app/api.py &
script:
 - pytest -v
after_script:
 - kill `pgrep python3`
